SET DEFINE ON
DEFINE APPLICATION_NAME = 'SIMPLE_SCHEDULER_DEMO'
DEFINE DEPLOY_VERSION = '1'

COLUMN CURRENT_SCHEMA       new_value CURRENT_SCHEMA      
SELECT sys_context('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA FROM DUAL;

SPOOL delete.&&APPLICATION_NAME..&&CURRENT_SCHEMA..log

--PRINT BIND VARIABLE VALUES
SET AUTOPRINT ON                    

--DISPLAY DBMS_OUTPUT.PUT_LINE OUTPUT
SET SERVEROUTPUT ON                 

WHENEVER SQLERROR EXIT FAILURE
WHENEVER OSERROR EXIT FAILURE

DELETE FROM JOB WHERE JOB_NAME = 'JOB_TASK_DEMO_01';
DELETE FROM TASK WHERE STATEMENT LIKE 'PKG_JOB_TASK_DEMO%';
COMMIT;

EXEC PKG_APPLICATION.delete_application_p(ip_application_name => '&&APPLICATION_NAME', ip_fail_on_not_found => 'N' );
--
SPOOL OFF
