REM INSERTING into JOB
SET DEFINE OFF;
DELETE FROM JOB WHERE JOB_NAME = 'JOB_TASK_DEMO_01';
Insert into JOB (JOB_ID,JOB_NAME,JOB_DESC,ENABLED_YN,JOB_STATUS,CURR_RUNDATE,CURR_JOB_EXEC_ID,PREV_RUNDATE,PREV_JOB_EXEC_ID) values (1,'JOB_TASK_DEMO_01','Sequential list of tasks','Y','N',null,null,null,null);

COMMIT;
