REM INSERTING into JOB_DETAIL
SET DEFINE OFF;
DELETE FROM JOB_DETAIL WHERE JOB_NAME = 'JOB_TASK_DEMO_01';
--
Insert into JOB_DETAIL (JOB_NAME,EXECUTION_ORDER,TASK_NAME,ENABLED_YN,EXPECTED_DURATION,"COMMENT") values ('JOB_TASK_DEMO_01', 1,'JOB_TASK_DEMO_TAB01'     ,'Y',NUMTODSINTERVAL( 1,'MINUTE'),NULL);
Insert into JOB_DETAIL (JOB_NAME,EXECUTION_ORDER,TASK_NAME,ENABLED_YN,EXPECTED_DURATION,"COMMENT") values ('JOB_TASK_DEMO_01', 2,'JOB_TASK_DEMO_TAB02'     ,'Y',NUMTODSINTERVAL( 1,'MINUTE'),NULL);
Insert into JOB_DETAIL (JOB_NAME,EXECUTION_ORDER,TASK_NAME,ENABLED_YN,EXPECTED_DURATION,"COMMENT") values ('JOB_TASK_DEMO_01', 3,'JOB_TASK_DEMO_TAB03'     ,'Y',NUMTODSINTERVAL( 1,'MINUTE'),NULL);
Insert into JOB_DETAIL (JOB_NAME,EXECUTION_ORDER,TASK_NAME,ENABLED_YN,EXPECTED_DURATION,"COMMENT") values ('JOB_TASK_DEMO_01', 4,'JOB_TASK_DEMO_TAB04'     ,'Y',NUMTODSINTERVAL( 1,'MINUTE'),NULL);
Insert into JOB_DETAIL (JOB_NAME,EXECUTION_ORDER,TASK_NAME,ENABLED_YN,EXPECTED_DURATION,"COMMENT") values ('JOB_TASK_DEMO_01', 5,'JOB_TASK_DEMO_TAB05'     ,'Y',NUMTODSINTERVAL( 1,'MINUTE'),NULL);
Insert into JOB_DETAIL (JOB_NAME,EXECUTION_ORDER,TASK_NAME,ENABLED_YN,EXPECTED_DURATION,"COMMENT") values ('JOB_TASK_DEMO_01', 6,'JOB_TASK_DEMO_TAB06'     ,'Y',NUMTODSINTERVAL( 1,'MINUTE'),NULL);
Insert into JOB_DETAIL (JOB_NAME,EXECUTION_ORDER,TASK_NAME,ENABLED_YN,EXPECTED_DURATION,"COMMENT") values ('JOB_TASK_DEMO_01', 7,'JOB_TASK_DEMO_TAB07'     ,'Y',NUMTODSINTERVAL( 1,'MINUTE'),NULL);
--
COMMIT;
