CREATE TABLE JOB 
(
  JOB_ID              NUMBER                  NOT NULL 
, JOB_NAME            VARCHAR2(100)           NOT NULL
, JOB_DESC            VARCHAR2(200)           NOT NULL 
, ENABLED_YN          VARCHAR2(1) DEFAULT 'Y' NOT NULL
, JOB_STATUS          VARCHAR2(1) DEFAULT 'N' NOT NULL  --NEW, RUNNING, FAIL, COMPLETE
--, TASK_ORDERING_TYPE  VARCHAR2(1) DEFAULT 'S' NOT NULL  --S:STRICTLY ORDERED, D:DEPENDENCY
, CURR_RUNDATE        DATE
, CURR_JOB_EXEC_ID    NUMBER
, PREV_RUNDATE        DATE
, PREV_JOB_EXEC_ID    NUMBER
, INSTANCE_ID         NUMBER(2,0)
, CONSTRAINT JOB_CK01 CHECK ( JOB_NAME = UPPER(JOB_NAME)      ) ENABLE VALIDATE
, CONSTRAINT JOB_CK02 CHECK ( ENABLED_YN IN ('Y','N')         ) ENABLE VALIDATE
, CONSTRAINT JOB_CK03 CHECK ( JOB_STATUS IN ('N','R','F','C') ) ENABLE VALIDATE
, CONSTRAINT JOB_PK   PRIMARY KEY (JOB_ID)
     USING INDEX
     ENABLE VALIDATE
, CONSTRAINT JOB_UK01 UNIQUE (JOB_NAME)
     USING INDEX
     ENABLE VALIDATE
)
;

