CREATE TABLE TASK_EXEC_HIST 
(
  TASK_EXEC_ID         NUMBER NOT NULL
, TASK_ID              NUMBER NOT NULL 
, STATUS               VARCHAR2(1) DEFAULT 'R' NOT NULL  --RUNNING, FAIL, COMPLETE
, COLLECTION_STARTED   TIMESTAMP(6) NOT NULL
, COLLECTION_COMPLETED TIMESTAMP(6)
, COLLECTION_DURATION  INTERVAL DAY(2) TO SECOND(6)
, ROWS_PROCESSED       NUMBER
, NOTES                VARCHAR2(200)
, JOB_EXEC_ID          NUMBER
)
;


CREATE UNIQUE INDEX TASK_EXEC_HIST_PK ON TASK_EXEC_HIST
(TASK_EXEC_ID);

ALTER TABLE TASK_EXEC_HIST ADD (
  CONSTRAINT TASK_EXEC_HIST_PK
  PRIMARY KEY
  (TASK_EXEC_ID)
  USING INDEX TASK_EXEC_HIST_PK
  ENABLE VALIDATE);

/*
ALTER TABLE TASK_EXEC_HIST ADD
(JOB_EXEC_ID          NUMBER
);
*/




  