CREATE TABLE TASK 
(
  TASK_ID        NUMBER NOT NULL 
, TASK_NAME      VARCHAR2(100) NOT NULL
, TASK_DESC      VARCHAR2(100) NOT NULL 
, DB_LINK        VARCHAR2(100)
, SRC_SYSTEM_NAME    VARCHAR2(100)
, STMT_TYPE      VARCHAR2(1) DEFAULT 'S' NOT NULL   --STATEMENT, BLOCK
, STATUS         VARCHAR2(1) DEFAULT 'N' NOT NULL  --NEW, RUNNING, FAIL, COMPLETE
, DEST_TABLE     VARCHAR2(30)
, DEST_SCHEMA    VARCHAR2(30)
, CURR_RUNDATE   DATE
, CURR_TASK_EXEC_ID    NUMBER
, PREV_RUNDATE   DATE
, PREV_TASK_EXEC_ID    NUMBER
, STATEMENT      VARCHAR2(4000)
)
;

CREATE UNIQUE INDEX TASK_UK01 ON TASK
(TASK_NAME);

CREATE UNIQUE INDEX TASK_PK ON TASK
(TASK_ID);

ALTER TABLE TASK ADD (
  CONSTRAINT TASK_CK01
  CHECK (TASK_NAME = UPPER(TASK_NAME) 
         AND DB_LINK = UPPER(DB_LINK)
         AND SRC_SYSTEM_NAME = UPPER(SRC_SYSTEM_NAME)
         AND DEST_TABLE = UPPER(DEST_TABLE)
         AND DEST_SCHEMA = UPPER(DEST_SCHEMA)
		 AND STMT_TYPE IN ('S','B','N','P')
		 AND STATUS IN ('N','R','F','C')
        )
  ENABLE VALIDATE,
  CONSTRAINT TASK_PK
  PRIMARY KEY
  (TASK_ID)
  USING INDEX TASK_PK
  ENABLE VALIDATE
)
;

ALTER TABLE TASK ADD (
  CONSTRAINT TASK_UK01
  UNIQUE 
  (TASK_NAME)
  USING INDEX TASK_UK01
  ENABLE VALIDATE
)
;

COMMENT ON COLUMN TASK.STMT_TYPE IS 'S:Statement; B:Block; N:No-parameter-procedure; P:Procedure (with out_rows parameter)';
